// Global error handling function 
let handleError = function(error) {
  console.log("An error has occured ☹️", error)
}